spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: root
    driverClassName: org.h2.Driver
    
logging:
  level:
    org:
      springframework:
        security: DEBUG

